recipedia-uofa/recipedia

.flowconfig
package.json
public/index.html
yarn.lock

Adds flow to project
Upgrades serialize-javascript package
closes #1 
closes #2

Add flow to project 

---

package.json
src/RecipediaApp.js
src/components/SearchBar.js
yarn.lock

Base token input

---

package.json
src/RecipediaApp.js
src/actions/search.js
src/components/RecipeView.js
src/components/SearchBar.js
src/constants/actionTypes.js
src/reducers/resultsReducer.js
src/reducers/rootReducer.js
src/reducers/searchReducer.js
yarn.lock

This PR adds the basic redux framework for showing recipe results when a search is executed (it gets mock results). It's not fully complete, but most of the boilerplate is there. You can see the transformation below
Before "Search"
After "Search"

Show results on "search"

---

client/src/configureStore.js

Filter events that change the search bar from the logger

Filter logger

---

client/package.json
client/src/App.test.js
client/src/RecipediaApp.js
client/src/actions/index.js
client/src/actions/search.js
client/src/actions/searchbar.js
client/src/components/RecipeCard.js
client/src/components/RecipeView.js
client/src/components/SearchBar.js
client/src/components/TokenCreator.js
client/src/configureStore.js
client/src/constants/actionTypes.js
client/src/constants/colours.js
client/src/index.css
client/src/index.js
client/src/models/SearchToken.js
client/src/models/diets.js
client/src/models/keywords.js
client/src/models/recipe.js
client/src/reducers/resultsReducer.js
client/src/reducers/rootReducer.js
client/src/reducers/searchbarReducer.js
client/src/serviceWorker.js
client/src/setupTests.js
client/src/styles/recipecard.module.css
client/src/styles/searchbar.module.css
client/src/types/states.js
client/yarn.lock

Add `prettier` linting to repo

Lint client

---

client/package.json
client/src/actions/searchbar.js
client/src/components/SearchBar.js
client/src/components/Token.js
client/src/components/TokenCreator.js
client/src/components/TokenInput.js
client/src/constants/actionTypes.js
client/src/models/SearchToken.js
client/src/models/diets.js
client/src/models/keywords.js
client/src/reducers/searchbarReducer.js
client/src/styles/searchbar.module.css
client/src/types/states.js
client/yarn.lock

This PR adds token rendering in the search bar, and ports the `react-customize-token-input` to use redux. It also adds delete functionality when the user presses the backspace key.
closes #9 
closes #25

Redux-enabled token rendering

---

client/src/actions/searchbar.js
client/src/components/Token.js
client/src/components/TokenInput.js
client/src/styles/searchbar.module.css

Fixed the styling for the search token. Still need to update the searchbar element to hold all of the tokens properly

Fixed Search Token Styling

---

client/src/components/Token.js
client/src/styles/searchbar.module.css

…he tokens will now wrap nicely. The input 'cursor' still needs to fix position

Fixed input token width with searchbar

---

client/src/components/TokenCreator.js
client/src/components/TokenInput.js

Add focus to search bar

---

client/src/RecipediaApp.js
client/src/components/Token.js
client/src/components/TokenInput.js
client/src/styles/searchbar.module.css

The sizing of the width of the search bar will stay in a "fixed" position (a percentage value) when in default mode and results view mode

Fixed the width sizing of the search bar

---

client/src/components/RecipeCard.js
client/src/components/RecipeView.js
client/src/models/recipe.js
server/db/cheatsheet.md
server/docker-compose.yml
server/package.json
server/src/app.js
server/src/bin/www.js
server/src/getAllIngredients.js
server/src/models/ingredient.js
server/src/models/recipe.js
server/src/query.js
server/yarn.lock

Adds flow types to the server. For now, I just copied the basic types from the client but in the future we might need a better way of keeping these consistent.
Fixes #45 loading issue
closes #16 
closes #45

Enable flow on server and fix server queries

---

server/jsconfig.json
server/package.json
server/src/app.js
server/src/dgraph-utils.js
server/src/matchRecipes.js
server/src/models/SearchToken.js
server/src/models/diets.js
server/src/models/keywords.js
server/src/models/recipe.js
server/src/query.js
server/yarn.lock

Implemented the `/recipes` endpoint to return recipes that match at least one passed ingredient.
Urls are of the form `localhost:9000/recipes/q=keyword_ingredient&q=keyword_ingredient&...`
closes #47

MVP recipe matching query

---

client/src/actions/search.js
client/src/actions/searchbar.js
client/src/components/RecipeCard.js
client/src/components/RecipeView.js
client/src/components/TokenCreator.js
client/src/components/TokenInput.js
client/src/models/SearchToken.js
server/src/app.js
server/src/dgraph-utils.js
server/src/matchRecipes.js

Also makes the client search on every entered / deleted token
closes #50

Call match query from client

---

server/src/query.js

Fix server container connection issues

---

client/src/actions/searchbar.js
client/src/components/SearchBar.js
client/src/constants/actionTypes.js
client/src/reducers/searchbarReducer.js
client/src/types/states.js
server/src/app.js
server/src/dgraph-utils.js
server/src/getAllIngredients.js
server/src/matchRecipes.js

Calls the `/ingredients` endpoint to fetch all valid ingredients. These are stored in the redux store.
Also adds ordering by the number of ingredients matched.

Store valid ingredients and order recipes

---

client/src/actions/search.js
client/src/actions/searchbar.js
client/src/components/RecipeCard.js
client/src/components/SearchBar.js
client/src/models/ingredient.js
client/src/reducers/searchbarReducer.js
client/src/types/states.js

Only allow the entry of valid ingredients into the search bar.
closes #55

Validate ingredients

---

client/src/RecipediaApp.js
client/src/components/Autocomplete.js
client/src/styles/autocomplete.module.css

Got all of the keywords to change based on their correct styling. Completed #67

Fixed the styling for the keywords in the autocomplete section (#67)

---

client/src/components/SearchBar.js
client/src/styles/recipecard.module.css
client/src/styles/searchbar.module.css

The basic tool tip error element has been implemented. Still not complete as the positioning will need to be decided. Worked on #69

Implemented an absolute elemnt for the tool tip error. (#69)

---

client/src/components/Autocomplete.js
client/src/components/SearchBar.js
client/src/components/TokenCreator.js
client/src/styles/searchbar.module.css

Move error tooltip inside TokenCreator

---

client/src/styles/searchbar.module.css

Completed the styling for the tool tip error. #69

Fixed tooltip error styling

---

client/package.json
client/src/components/Autocomplete.js
client/src/models/autocomplete.js
client/yarn.lock

Applies a strict substring matching algorithm for autocomplete suggestions. Matches are scores based on a simple algorithm over the matching indices, with matches later in the string being penalised.
closes #65

Strict autocomplete

---

client/src/components/RecipeCard.js
client/src/styles/recipecard.module.css

Fixed the issue (#83).
Implemented after (#84)

Fixed the styling for the mac ingredients in the recipe boxes

---

client/src/actions/searchbar.js
client/src/components/Autocomplete.js
client/src/components/RecipeCard.js
client/src/components/SearchBar.js
client/src/components/TokenCreator.js
client/src/components/UserGuide.js
client/src/constants/actionTypes.js
client/src/models/autocomplete.js
client/src/models/input.js
client/src/reducers/searchbarReducer.js
client/src/types/states.js
server/src/matchRecipes.js

Completes a with the top autocomplete suggestion when the user presses TAB.

Autocomplete TAB completion

---

client/src/actions/searchbar.js
client/src/components/Autocomplete.js
client/src/components/RecipeCard.js
client/src/components/TokenCreator.js
client/src/constants/actionTypes.js
client/src/models/autocomplete.js
client/src/reducers/searchbarReducer.js
client/src/types/states.js

Enables the up and down arrows to select ingredients from the suggestion list and complete them when they press TAB. closes #87

Autocomplete arrow selection and completion

---

client/src/RecipediaApp.js
client/src/actions/searchbar.js
client/src/components/SearchBar.js
client/src/models/input.js
client/src/styles/autocomplete.module.css
client/src/styles/searchbar.module.css

Implement the functionality to prevent duplicate search tokens to be created. (#79, #31  )
Also enhanced the style of the searchbar to have the button on the right and the autocomplete styling is to have similar color scheme as the rest of the sight.

Prevent SearchToken duplication in Searchbar

---

server/package.json
server/src/__tests__/matchRecipes.test.js
server/src/matchRecipes.js
server/yarn.lock

Adds `jest` testing to the server side code and creates a bracket-checking test for each of the match query types. 
closes #17

Match query bracket testing

---

client/src/RecipediaApp.js
client/src/actions/searchbar.js
client/src/components/Token.js
client/src/components/TokenInput.js
client/src/components/UserGuide.js
client/src/models/SearchToken.js
client/src/styles/recipecard.module.css
client/src/styles/searchbar.module.css

We are now able to delete search bar tokens by clicking the X on the token (#59 )

Implement searchtoken deletion

---

client/src/components/Token.js
server/src/__tests__/matchRecipes.test.js
server/src/dgraph-utils.js
server/src/matchRecipes.js

Handle `NOT` tokens such that no blacklists are included in the results
closes #104

Match query blacklisting

---

client/src/__tests__/autocomplete.test.js
client/src/components/LoadingOverlay.js
client/src/components/SearchBar.js
client/src/models/autocomplete.js
client/src/styles/loadingbar.module.css

Sanitize the input for consumption in the matching query
closes #108

Autocomplete regex sanitization

---

client/src/RecipediaApp.js
client/src/components/LoadingOverlay.js
client/src/components/RecipeCard.js
client/src/components/SearchBar.js
client/src/models/suggestions.js
client/src/reducers/resultsReducer.js
client/src/types/states.js

Alternate to #98. We extract the ingredient suggestions as the most prevalent missing ingredients from the matched recipes.

Suggestions from matched recipes

---

client/src/RecipediaApp.js
client/src/actions/searchbar.js
client/src/components/SuggestionToken.js

Hook up some basic suggestion tokens to the UI
closes #98

Non-styled suggestion token

---

client/src/RecipediaApp.js
client/src/components/SuggestionToken.js
client/src/styles/searchbar.module.css

After @jhryniw completed the suggestion token functionality, I have added the styling to enhance the look of the feature so that it matches the rest of the site. (#99 )

Implement suggestion styling (#99)

---

client/src/actions/searchbar.js
client/src/components/Autocomplete.js
client/src/components/TokenCreator.js

Allow the site to receive onClick events from the autocomplete box. (#119 )

Implemented the onClick event for autocomplete suggestions (#119)

---

client/src/actions/searchbar.js
client/src/components/TokenCreator.js
client/src/styles/searchbar.module.css

Fixed an issue where there would be an "invisible box" that would block the user from deleting search tokens

Fixed error tooltip

---

client/package.json
client/src/actions/index.js
client/src/actions/searchbar.js
client/src/actions/url.js
client/src/components/SuggestionToken.js
client/src/configureStore.js
client/src/constants/actionTypes.js
client/src/reducers/searchbarReducer.js
client/src/syncUrl.js
client/yarn.lock

Syncs the searchbar tokens with the URL. If a new url is entered it is parsed and populates the initial app state.
closes #113

Plaintext shared urls

---

client/package.json
client/src/models/SearchToken.js
client/src/models/__tests__/searchtoken.test.js
client/src/models/diets.js
client/src/reducers/searchbarReducer.js
client/yarn.lock

- Displays diets in regular casing (with spaces) for autocomplete
- Displays suggested diets when there is no search input, but we expect a diet
closes #136 
closes #137

Diet autocomplete

---

server/.flowconfig
server/db/data/recipedia.schema
server/flow-typed/npm/jest_v25.x.x.js
server/package.json
server/src/__tests__/helpers.js
server/src/__tests__/matchRecipes.test.js
server/src/matchRecipes.js
server/src/models/SearchToken.js
server/src/models/__tests__/diets.test.js
server/src/models/diets.js
server/yarn.lock

Makes diet search clauses functional.
Adds testing to ensure queries have full variable usage.
closes #112

Implement diet filtering

---

client/flow-typed/npm/ramda_v0.27.x.js
client/src/models/SearchToken.js
client/src/models/__tests__/searchtoken.test.js
client/src/models/__tests__/suggestions.test.js
client/src/models/diets.js
client/src/models/input.js
client/src/models/keywords.js
client/src/models/recipe.js
client/src/reducers/resultsReducer.js
client/src/reducers/searchbarReducer.js
client/src/syncUrl.js
server/flow-typed/npm/ramda_v0.27.x.js
server/src/dgraph-utils.js
server/src/models/SearchToken.js
server/src/models/category.js
server/src/models/diets.js
server/src/models/keywords.js

- Simplifies token encoding for simple ingredients. Makes for a nicer interface in the url bar
- Adds token validation for tokens entered via the URL
- SearchToken.isValid function, with testing
closes #131

Succinct query encoding

---

client/src/RecipediaApp.js
client/src/components/RecipeCard.js
client/src/styles/loadingbar.module.css
client/src/styles/recipecard.module.css
client/src/styles/searchbar.module.css

Implemented most of the suggestions from the initial feedback. Still need to fix the growth of the additional ingredients on the recipe cards. (#138 )
Implemented "Gold" ingredients when matching a full set of ingredients with a recipe. (#139 )

Frontend client enhancements

---

client/src/components/RecipeCard.js
client/src/constants/colours.js

Adds coloured styling for the nutriscore
- Nutriscores from 0-29 are red
- Nutriscores from 30-69 are yellow
- Nutriscores from 70-100 are green

Coloured nutriscore circle

---

client/src/models/__tests__/searchtoken.test.js
client/src/reducers/searchbarReducer.js

Fix diet autocomplete bug

---

client/src/components/RecipeCard.js
client/src/styles/recipecard.module.css

Fixed some issues with recipe cards where there is a dot dot dot overlay in front of ingredients

Fixed dot dot dot overlap

---

client/src/RecipediaApp.js
client/src/components/RecipeView.js
client/src/components/SearchBar.js
client/src/components/UserGuide.js
client/src/styles/loadingbar.module.css
client/src/styles/recipecard.module.css
client/src/styles/recipediasmallscreens.module.css
client/src/styles/searchbar.module.css
client/src/styles/userguide.module.css

The website is still not 100% optimized for mobile, but you will be able to view it on a mobile screen like normal. (#153 )

Implement mobile window sizing
